---
name: release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Tableau Connector Plugin SDK
        uses: actions/checkout@v4
        with:
          repository: tableau/connector-plugin-sdk
          ref: tableau-2023.2

      - name: Checkout CubeJS Tableau JDBC connector
        uses: actions/checkout@v4
        with:
          path: cubejs-tableau-jdbc

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Package the connector
        working-directory: connector-packager
        run: |
          python -m venv .venv
          source ./.venv/bin/activate
          pip install .
          python -m connector_packager.package ../cubejs-tableau-jdbc/cubejs_jdbc -v --dest /tmp/
          echo "TACO_FILE=$(find /tmp/ -name 'cubejs*.taco' | head -n 1)" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.TACO_FILE }}
          generate_release_notes: true
