---
name: release
on:
  workflow_dispatch:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Tableau Connector Plugin SDK
        uses: actions/checkout@v3
        with:
          repository: tableau/connector-plugin-sdk
          ref: tableau-2023.2

      - name: Checkout CubeJS Tableau JDBC connector
        uses: actions/checkout@v3
        with:
          path: cubejs-tableau-jdbc

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Package the connector
        working-directory: connector-packager
        run: |
          python -m venv .venv
          source ./.venv/bin/activate
          pip install .
          python -m connector_packager.package ../cubejs-tableau-jdbc/cubejs_jdbc --dest ../cubejs-tableau-jdbc/packaged_connector -v

      - name: Upload the taco
        uses: actions/upload-artifact@v3
        with:
          name: cubejs_jdbc.taco
          path: ../cubejs-tableau-jdbc/packaged_connector/cubejs_jdbc*.taco
          if-no-files-found: error
